### ISSUE TITLE
About jc branch of the EPANET-RTX

### ISSUE THREAD

**Issue by YangZhang18** [OpenWaterAnalytics/epanet-rtx#101]
Does anyone have the JC branch？@SamHatchett I think you may be have , do you ?

**Comment by YangZhang18** [comment]
And what does the identifiers like "ow_project" mean ? I can not find in header files . How can I ues them ?

**Comment by samhatchett** [comment]
I no longer have that branch. The "ow_..." calls refer to a threadsafe version of epanet here: https://github.com/samhatchett/EPANET/tree/owa_netBuilder

**Comment by YangZhang18** [comment]
Thank you@samhatchett
