### ISSUE TITLE
Error LNK2019 when using epanet-rtx.lib

### ISSUE THREAD

**Issue by YangZhang18** [OpenWaterAnalytics/epanet-rtx#103]
I had got the rpanet-rtx.lib , but when I used it in the validator.cpp , the vs2012 shows the error LNK2019 like : epanet-rtx.lib(Model.obj) : error LNK2019: Cannot resolve the external symbol "public: __cdecl RTX::Dma::Dma(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??0Dma@RTX@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)，The symbol in the function "public: void __cdecl RTX::Model::initDMAs(void)" (?initDMAs@Model@RTX@@QEAAXXZ) is referenced
......

1>epanet-rtx.lib(EpanetModel.obj) : error LNK2019: Cannot resolve the external symbol  OW_newModel，The symbol in the function "public: __cdecl RTX::EpanetModel::EpanetModel(void)" (??0EpanetModel@RTX@@QEAA@XZ) is referenced
......
Is that cause my lib get wrong?

**Comment by samhatchett** [comment]
Compilation and linking issues have more to do with your IDE or development setup than with issues in the code. Reading through a good tutorial on those subjects should help.

**Comment by YangZhang18** [comment]
Thanks , I would try and try .

**Comment by YangZhang18** [comment]
When I used the threadsafe version of epanet , which source files should I ues ? "en_legacy_api.c" or just used the "epanet.c" . And what does the  "networkBuilder.c" used for ?@samhatchett

**Comment by YangZhang18** [comment]
Hi Sam,

```
       Could you tell me what compiler you used to compile? And does the breach "owa net_builder" of epanet can be compiling successful in windows?
```

---

发件人: Sam Hatchett notifications@github.com
发送时间: 2016年9月23日 10:28
收件人: OpenWaterAnalytics/epanet-rtx
抄送: YangZhang18; Author
主题: Re: [OpenWaterAnalytics/epanet-rtx] Error LNK2019 when using epanet-rtx.lib (#103)

Compilation and linking issues have more to do with your IDE or development setup than with issues in the code. Reading through a good tutorial on those subjects should help.

―
