### ISSUE TITLE
problems where valid range with a clock will not interpolate across day boundaries

### ISSUE THREAD

**Issue by jamesuber** [OpenWaterAnalytics/epanet-rtx#105]
![screen shot 2016-11-18 at 8 25 49 am](https://cloud.githubusercontent.com/assets/2408457/20431579/caa23226-ad68-11e6-83e3-07b795feb908.png)

this is identified for Louisville.

**Comment by jamesuber** [comment]
This is related to the valid range having a clock. If the valid range clock is removed, and the resampling clock is added to the subsequent time series (in this case a stats), then the gaps go away and stats seems to interpolate normally across the gaps created by the dropped points.

So not sure this is a bug. But clocks and valid ranges seem to be problematic?

**Comment by samhatchett** [comment]
this is a difficult edge case involving the set of filters that can drop points. how to expand the source series search space intelligently/efficiently. right now we use a "range-duration" expansion, but probably need to move to an iterative fwd/backwd search algo.

**Comment by samhatchett** [comment]
settled on using existing code to solve the problem. just swap out the clock, seek to next valid point, restore the clock.
![screen shot 2016-11-22 at 11 19 54 am](https://cloud.githubusercontent.com/assets/2386549/20532779/26c468ec-b0a9-11e6-98e9-40fd68ebfaa8.png)
