### ISSUE TITLE
gain modulartimeseries units

### ISSUE THREAD

**Issue by jamesuber** [OpenWaterAnalytics/epanet-rtx#109]
gain does not properly set its units when fed by a raw data source (and thus w/o a clock). 

for example, a data source with gpm units fed to a dimensionless gain, shows resulting units as "no units" and all units are possible. Explicitly setting the output gain units to gpm is allowed and seems to work.

Gain works properly when fed by a constant timeseries with a clock.

**Comment by samhatchett** [comment]
can't replicate. is there more to this issue, like loading from a saved state?
