### ISSUE TITLE
How to Use EPANET-RTX on windows desktop?

### ISSUE THREAD

**Issue by sadaarc** [OpenWaterAnalytics/epanet-rtx#112]
Can you please send me the steps to be followed to run this on windows desktop.
It would be great if you could send a document for usage.

Thanks in advance.

**Comment by samhatchett** [comment]
Sorry, we do not currently support building on Windows. It is completely feasible, however, as everything is standard C++ and CMake is the build tool. If you would like to make changes necessary for windows compilation and submit a PR, it would be most welcome!

**Comment by sadaarc** [comment]
Okay Thank you
