### ISSUE TITLE
MysqlPointRecord::reset()

### ISSUE THREAD

**Issue by jamesuber** [OpenWaterAnalytics/epanet-rtx#13]
reset() does "TRUNCATE TABLE points" which erases all the points in the PointRecord, ignoring the series_id (or, the timeseries_meta information).

This coarse strategy seems to prohibit, for example, sequentially adding new ModularTimeSeries to the same PointRecord, because that PointRecord is truncated every time a new ModularTimeSeries is created and connected to a source (ModularTimeSeries::setSource and ModularTimeSeries::setUnits both logically use reset() ).

Is it logical for reset() to do a more complicated DELETE FROM `points` WHERE `series_id` = <id of MysqlPointRecord name> ? That would seem to fix any use of resetCache by a ModularTimeSeries to only affect the relevant data in the table.

**Comment by samhatchett** [comment]
probably need to modify the reset() method -- reset(const string& name)
