### ISSUE TITLE
MovingAverage::Points not immediately reflecting change of units

### ISSUE THREAD

**Issue by jamesuber** [OpenWaterAnalytics/epanet-rtx#15]
In the timeseries_demo application, it is illustrating the change in units using the MovingAverage->setUnits method,

movingAverage->setUnits(RTX_GALLON_PER_MINUTE);
  printPoints( movingAverage->points(start, start+240) );

but the points method is returning points (and printPoints is printing them out) in the original units before the change. 

When these same points are persisted, however, the units change is in effect.

**Comment by samhatchett** [comment]
PointRecord was not resetting like it should have.
