### ISSUE TITLE
getting the point after using pointAfter

### ISSUE THREAD

**Issue by jamesuber** [OpenWaterAnalytics/epanet-rtx#16]
the pointAfter methods for the ModularTimeSeries and derived classes work reliably when it is given a time that is valid. But when the clock is regular you can get an invalid point if you ask for one that is outside the time range of validity. I think that point validity is ensured if the time t >= tstart where tstart is the time of the first DB entry. 

This much is clear from the cerr reminders to "check point availability first" - but it will be useful sometimes to know how to determine a valid time, such as when you want to do processing on an entire timeseries and you don't know much about it other than it's in the DB. A method that only checks for point validity and iterates isn't going to be much fun (and possibly never ending).

One can solve this by getting down to the underlying TimeSeries and PointRecord, using the boost dynamic pointer cast to iteratively check upstream objects for whether or not it is a valid ModularTimeSeries. Sam pointed this out to me and provided the following code snippet that iterates beginning from a ModularTimeSeries (thanks, Sam):

```
  // find a valid future time, else go on to the next TimeSeries
  TimeSeries::sharedPointer candidate = aTimeSeries;
  ModularTimeSeries::sharedPointer castTS;
  while ((castTS = boost::dynamic_pointer_cast<ModularTimeSeries>(candidate))) {
    candidate = castTS->source();
  }
  // not a valid modular series
  Point aPoint = candidate->pointAfter(0);
```

Well, that works great. Should it be in RTX as an enhancement?

One possibility is to provide a ModularTimeSeries method that allows one to check for a valid range of times, like ModularTimeSeries::validTimeRange() that would return, somehow, the first time and the last time of the PointRecord.

**Comment by samhatchett** [comment]
this is all resolved in the [dev] branch
