### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by wzjlab** [OpenWaterAnalytics/epanet-rtx#21]
Hi. I'm a beginner.
I have modified the makefile (# **\* Files) with new code files.
//
RTX_HEADERS = AggregatorTimeSeries.h BufferPointRecord.h Clock.h ConfigFactory.h ConstantSeries.h CurveFunction.h DbPointRecord.h DequePointRecord.h Element.h EpanetModel.h EpanetSyntheticModel.h FirstDerivative.h IrregularClock.h Junction.h Link.h MapPointRecord.h Model.h ModularTimeSeries.h MovingAverage.h MysqlPointRecord.h Node.h OdbcPointRecord.h OffsetTimeSeries.h Pipe.h Point.h PointRecord.h Pump.h Resampler.h Reservoir.h SineTimeSeries.h Tank.h TimeSeries.h Units.h Valve.h Zone.h rtxExceptions.h rtxMacros.h

RTX_SRC = AggregatorTimeSeries.cpp BufferPointRecord.cpp Clock.cpp ConfigFactory.cpp ConstantSeries.cpp CurveFunction.cpp DbPointRecord.cpp DequePointRecord.cpp Element.cpp EpanetModel.cpp EpanetSyntheticModel.cpp FirstDerivative.cpp IrregularClock.cpp Junction.cpp Link.cpp MapPointRecord.cpp Model.cpp ModularTimeSeries.cpp MovingAverage.cpp MysqlPointRecord.cpp Node.cpp OdbcPointRecord.cpp OffsetTimeSeries.cpp Pipe.cpp Point.cpp PointRecord.cpp Pump.cpp Resampler.cpp Reservoir.cpp SineTimeSeries.cpp Tank.cpp TimeSeries.cpp Units.cpp Valve.cpp Zone.cpp

RTX_OBJS = AggregatorTimeSeries.o BufferPointRecord.o Clock.o ConfigFactory.o ConstantSeries.o CurveFunction.o DbPointRecord.o DequePointRecord.o Element.o EpanetModel.o EpanetSyntheticModel.o FirstDerivative.o IrregularClock.o Junction.o Link.o MapPointRecord.o Model.o ModularTimeSeries.o MovingAverage.o MysqlPointRecord.o Node.o OdbcPointRecord.o OffsetTimeSeries.o Pipe.o Point.o PointRecord.o Pump.o Resampler.o Reservoir.o SineTimeSeries.o Tank.o TimeSeries.o Units.o Valve.o Zone.o
//

I compile code with clang in Ubuntu. It comes the error.
Can you tell me how to solve it?

../../src/OdbcPointRecord.cpp:405:32: error: expected a class or namespace
      Point::Qual_t q = Point::Qual_t::good; // todo -- map to rtx quality types

**Comment by samhatchett** [comment]
Looks like a dependency issue. We should make sure that Point.h is included in the right place.

**Comment by wzjlab** [comment]
It seems that it is not the included problem.
I write a demo for testing this.

//
#include "Point.h"
int main()
{  
    Point::Qual_t q = Point::Qual_t::good;
    return 0;
}
//

But I can't compile it in Ubuntu all the same because of "Point::Qual_t q = Point::Qual_t::good;"

However, I successfully compiled this demo with Visual C++ 6.0 in Windows. 
So I wonder if it is the problem of compiler configuration.

**Comment by samhatchett** [comment]
the issue might be that this version relies on the compiler using the GNU std c++ library, and will not compile with the LLVM C++ library

**Comment by sdteffen** [comment]
Use of 
Point::Qual_t q = Point::good;
instead of
Point::Qual_t q = Point::Qual_t::good;
fixed the problem for me.
