### ISSUE TITLE
~MysqlPointRecord

### ISSUE THREAD

**Issue by jamesuber** [OpenWaterAnalytics/epanet-rtx#24]
The mysqlpointrecord destructor hit some sort of snag when calling the driver threadEnd method. Here's
![PastedGraphic-2](https://f.cloud.github.com/assets/2408457/398732/89b66574-a85e-11e2-9b7f-082f5b67661a.png)
 a screen shot.

**Comment by samhatchett** [comment]
this was a failed attempt to use threaded mysql driver. code is excluded as of 1c66beb79adb
