### ISSUE TITLE
no op. BufferPointRecord::addPoint 

### ISSUE THREAD

**Issue by jamesuber** [OpenWaterAnalytics/epanet-rtx#30]
Don't really know if this is a potential bug. But this noop. addpoint() method is being used. I noticed that and printed out some debug info - 

BufferPointRecord::addPoint() -- no point added for TimeSeries Dudley 1080 Station Flow (ranged)
BufferPointRecord::addPoint() -- no point added for TimeSeries Dudley 1080 Station Flow (ranged)
BufferPointRecord::addPoint() -- no point added for TimeSeries Dudley 1080 Station Flow (resampled)
BufferPointRecord::addPoint() -- no point added for TimeSeries Dudley 1080 Station Flow (resampled)

etc...

**Comment by samhatchett** [comment]
The noop ensures that buffer never violates point contiguity. A stack trace here would be helpful since it looks like the edge case of single point insertion is happening frequently with this use case.

**Comment by jamesuber** [comment]
Here's one -

![untitled](https://f.cloud.github.com/assets/2408457/605229/0455297a-cd10-11e2-9f9f-8823b38af58f.png)
