### ISSUE TITLE
ignore list for flow_measures

### ISSUE THREAD

**Issue by jamesuber** [OpenWaterAnalytics/epanet-rtx#32]
It is useful to specify flow measures and yet not have them be included in zone delineation or demand calculation. One reason is that a flow measure data might not be good enough for demand estimation, but still useful for model comparision. Another is that you might want to break a zone boundary on purpose, because of some undesirable property of that zone, or even just for sensitivity studies.

**Comment by samhatchett** [comment]
fixed in a192a1816695
