### ISSUE TITLE
Beginning at EPANET-RTX

### ISSUE THREAD

**Issue by SergioAnaya456** [OpenWaterAnalytics/epanet-rtx#34]
Good afternoon, my name es Sergio Anaya, and I want you to help me in my work. I'm new to programming in Epanet-RTX toolkit, and would like an explanation step by step what I have to do to run a hydraulic network with SCADA system, for example.

How do I call the libraries?
How scada link tags of a hydraulic model element?
How the simulation performed?

thanks, I appreciate your help

**Comment by sdteffen** [comment]
Sergio has asked the same questions in issue #5 and received several responses there.
Sergio, did you follow Jinduan's instructions how to build EPANET-RTX on Windows?
https://github.com/OpenWaterAnalytics/epanet-rtx/wiki/EPANET-RTX-on-Windows
Do you have further questions/problems?
