### ISSUE TITLE
Is GSL a prerequisite?

### ISSUE THREAD

**Issue by sdteffen** [OpenWaterAnalytics/epanet-rtx#36]
The documentation lists GSL as a prerequisite (http://openwateranalytics.github.io/epanet-rtx/ ). However, I cannot find any references in the sources. Does the documentation need an update?

**Comment by samhatchett** [comment]
Good catch. We originally were using GSL for the moving average filter, but switched to boost instead since that was already being linked in. There's a bigger picture here, I think, about overhauling the documentation and specs. I will remove the line about GSL in the meantime.
