### ISSUE TITLE
lack of folder "epanet" in epanet-rtx-workshop

### ISSUE THREAD

**Issue by dahuacai** [OpenWaterAnalytics/epanet-rtx#39]
I'm sorry, I  have a problem that why not have folder:“epanet” in the folder “src”？i find some functions have been changed in epanet.c,such as the  added  function “ENgetdemandpattern()” , but i can not find this from the source code files。

**Comment by samhatchett** [comment]
it looks like you're using a branch from 1c7159e088729d90c495faff3527ff7f83433f88 -- this is very old. If you're interested in testing and/or developing, I would recommend using the "1.1_preproduction" branch here, and linking to the OpenWaterAnalytics/epanet library on branch "next".

**Comment by dahuacai** [comment]
OK ,thanks very much!

------------------ 原始邮件 ------------------
发件人: "Sam Hatchett"notifications@github.com; 
发送时间: 2014年7月10日(星期四) 晚上11:01
收件人: "OpenWaterAnalytics/epanet-rtx"epanet-rtx@noreply.github.com; 
抄送: "蔡华强"1074628367@qq.com; 
主题: Re: [epanet-rtx] lack of folder "epanet" in epanet-rtx-workshop (#39)

it looks like you're using a branch from 1c7159e -- this is very old. If you're interested in testing and/or developing, I would recommend using the "1.1_preproduction" branch here, and linking to the OpenWaterAnalytics/epanet library on branch "next".

&mdash;
