### ISSUE TITLE
I don't konw the relationship between OdbcPointRecord and OdbcPreparedPointRecord?

### ISSUE THREAD

**Issue by dahuacai** [OpenWaterAnalytics/epanet-rtx#40]
Hello ,I am using Epanet-RTX to develop my program .  But now, I have a question ,I don't konw the relationship between OdbcPointRecord and OdbcPreparedPointRecord? still the OdbcDirectPointRecord? How to Use them? Thanks for  your reply.

**Comment by samhatchett** [comment]
OdbcPointRecord is a semi-abstract class supporting the common functions of the "Direct" and "Prepared" variants. in practice, we find the Direct execution is faster depending on the database the utility is using.
