### ISSUE TITLE
Question about the direction  of pipe flow in the scada db？

### ISSUE THREAD

**Issue by dahuacai** [OpenWaterAnalytics/epanet-rtx#41]
Hello,my name is caihuaqiang，When  I try to apply  RTX to a real water supply network ，I find that the values of  the pipes flow in the  scada db all are postive， that is to say，they dont't have direction，how to fix it to adapt to RTX？ it's a significant problem to me，so  thanks very much for replying to me as soon as possible！

**Comment by jamesuber** [comment]
Briefly, you should ensure that all pipes that will be assigned to flow measures, are oriented in the direction of the  flow measure.

**Comment by samhatchett** [comment]
Correct. Flow measures assume the same orientation of the pipe as it is defined in the model.

**Comment by dahuacai** [comment]
OH,I know,thanks very much!.All the members in RTX term are my teachers and idols!
One more thing,for speeding the process of storaging results ,I try to change the way to save results by batch process for a big supply network (nodes>50000,pipes>50000),now it will complete a synthetic simulation and storage results(results nums >260000)  in one minute,if not try to improve the method to save,by single insert process,it will waste more than ten hours for one simulation and results store, i have share the code in “https://github.com/dahuacai/epanet-rtx-1.1-public_beta_dhc” just now .And ,there are some other improvements which i am not sure whether they are completely correct and reasonable or whether it is helpful for RTX,please evacuate to point out mistakes so that they can be corrected.

**Comment by dahuacai** [comment]
sorry i find that i can not upload my codes in china  a moment ago, although tried any times.

**Comment by samhatchett** [comment]
@dahuacai -- we are looking forward to seeing your modifications. However, it appears that your new branch is not forked from this repo, which makes comparisons and pull requests quite difficult. I'm not sure what to suggest here, though I know it's possible to "play back" commits into a proper branch as long as the root contents are identical.

**Comment by dahuacai** [comment]
maybe recently, it cannot upload codes to github privately in our country , I wiil email to you and sent the main modified file to you right now.

**Comment by samhatchett** [comment]
thanks!

**Comment by dahuacai** [comment]
Hello , Mr samhatchett , Last week I Have sent  my codes and some  added question to your Gmail,  but I am not sure whether you had received it ? Sorry.
