### ISSUE TITLE
General Questions?

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/epanet-rtx#5]
if you have any general, open-ended questions, feel free to create a new issue (tag it "question").

**Comment by SergioAnaya456** [comment]
Good afternoon, my name es Sergio Anaya, and I want you to help me in my work. I'm new to programming in Epanet-RTX toolkit, and would like an explanation step by step what I have to do to run a hydraulic network with SCADA system, for example.

How do I call the libraries?
How scada link tags of a hydraulic model element?
How the simulation performed?

thanks, I appreciate your help

**Comment by nexusbr-geoengenharia** [comment]
Sergio:

We have exactly the same questions. We can work together to come to step by step and release to the community.

**Comment by SergioAnaya456** [comment]
OK. Howwever we're need a baseline to start. which is the first step?

**Comment by nexusbr-geoengenharia** [comment]
I already download the components, now I need to talk to the Linux specialist to see if he can help how to compile it.

In with country you are located? I am in Brazil, our website is nexusbr.com

**Comment by nexusbr-geoengenharia** [comment]
Do you have a Linux specialist that can help in this process?

**Comment by SergioAnaya456** [comment]
I'm from colombia, but I want to implement the toolkit on Windows, however could you send me the components that you downloaded?.

thanks and counting on me to continue the process.

**Comment by SergioAnaya456** [comment]
My email is zizou10_5@hotmail.com

**Comment by nexusbr-geoengenharia** [comment]
Sergio: 

You can find it and download here at https://github.com/OpenWaterAnalytics/epanet-rtx

**Comment by SergioAnaya456** [comment]
thanks, were outstanding start implementing the tool, you can tell me where do I download the software C++?

**Comment by nexusbr-geoengenharia** [comment]
You are welcome. In the same repository at https://github.com/OpenWaterAnalytics/epanet-rtx/tree/master/src

**Comment by SergioAnaya456** [comment]
thanks again. You have been a great help. Now just trying to program the tool.

**Comment by JinduanChen** [comment]
I did a Windows port earlier this year. See the branch "jc".

**Comment by SergioAnaya456** [comment]
thanks but I'm a beginner in this toolitk and I want your help step by step if possible. I found the folder "jc", what´s the next step such that you can run the program in windows.

**Comment by jamesuber** [comment]
Hi Sergio,

We all want to help you out, but to be honest this isn't a project that has the means to provide such basic support. You will need to be willing to do a significant amount of "homework" I believe, in order to be able to make productive use of RTX. It sounds like you do not have a lot of background working with software libraries, IDEs, and developing your own programs. I also assume that you do not currently know the C++ language, since you were asking how to obtain that. You will need to correct all of these deficiencies, and likely more, prior to using RTX.

I would suggest that you start by gaining experience programming in C and C++ using an integrated development environment (IDE) like Visual Studio. 

This is not going to be done in a few weekends, so I'd encourage you to be prepared for a real investment. On the other hand, all of us have had to start from there at one point, so it's really up to you.

Lastly, we have certainly discussed the need for better documentation of RTX, for just these circumstances. That will be coming with time. But even if we had that now, my above statements would still likely apply.

Good luck!
Jim Uber

**Comment by SergioAnaya456** [comment]
HI Jim

I have experience developing applications with the EPANET toolkit for visual basic platform. with respect to C ++, I know the language, I just thought I did not have the software, but if I have the visual studio.

I have doubts about the connection to the SCADA system, and so my interest in learning about EPANET-rtx.

Thanks

**Comment by JinduanChen** [comment]
Sergio, 

VB and Cpp are quite different, and I suggest the same as Jim did - you may want invest some time in basic concepts like compiler, linker,  and makefile/project file, and then you'll be able to compile and run rtx examples.

**Comment by sdteffen** [comment]
Hi Nexusbr,

which flavor of Linux do you use? I've added short instructions how to build EPANET-RTX on Ubuntu to http://epanet.de/developer/ooten.html#epanet-rtx
Note that a successful build currently depends on an updated Makefile See my pull request https://github.com/OpenWaterAnalytics/epanet-rtx/pull/35

Jinduan: Would it be possible to merge your Visual C++ changes into Master? Alternatively, add a dummy vs2012 folder with a readme file to master telling people where to find that code and/or add this information to the "official documentation".

**Comment by JinduanChen** [comment]
Hi sdteffen,

I have a readme file in the "jc" branch showing how to resolve the dependencies on Win64. Let us ask Sam to put a note in Master's doc telling people where it is.

As for the merge, we need to put more efforts in the source code for multi-platform compilation... hope it'll get done some time in the future.

**Comment by samhatchett** [comment]
Thought i'd pop in here for a second :)

I've put Jinduan's guide in wiki format here: https://github.com/OpenWaterAnalytics/epanet-rtx/wiki/EPANET-RTX-on-Windows -- and if anyone else wants to contribute to the wiki, feel free! 

... also, I will (hopefully soon) be rolling out some bug fixes an enhancements we've made over the past several months while getting our commercial product put together. I imagine a lot of the documentation will have to be regenerated, and I'll probably suggest some version numbering to reflect api changes. I'm just so glad that there seems to be some interest from the community in using this code.

**Comment by JinduanChen** [comment]
Thank you Sam for the formatting.

**Comment by YangZhang18** [comment]
Where can I find the the branch  "jc", and I could not find the guide which writed by Jinduan in  https://github.com/OpenWaterAnalytics/epanet-rtx/wiki/EPANET-RTX-on-Windows

**Comment by samhatchett** [comment]
@YangZhang18 sorry, the link should work now. had to re-enable the wiki feature

**Comment by YangZhang18** [comment]
@samhatchett when I build rtx.lib , the vs2012 showed the error c4430: The lack of type specifier, in epanet.h . What should I do ?

**Comment by YangZhang18** [comment]
Just cause the version of vs?

**Comment by YangZhang18** [comment]
@samhatchett @JinduanChen Would you help me ?

**Comment by samhatchett** [comment]
Sorry @YangZhang18 but this type of support is a little beyond our resources at the moment. The project has evidently diverged from the windows build instructions provided by Jinduan, and we don't have any windows people engaged in the project. But it sounds like you might benefit from some basic compilation/IDE education. This project is not plug-and-play currently so you'll probably need some more time to learn about compilation to make this work.
