### ISSUE TITLE
Make level output state a time series and not an offset of head

### ISSUE THREAD

**Issue by jamesuber** [OpenWaterAnalytics/epanet-rtx#69]
This would fix the issue that if head is not saved, you can't produce a level, which seems strange until someone explains it to you.

While we're at it, why not change the names of all the model state series for junction/link/tank/reservoir elements to be like N/L + <node id> + type for uniformity?

**Comment by samhatchett** [comment]
As for the second issue here, regarding naming convention, this is currently implemented in RTX. certain calling code may not adhere.
