### ISSUE TITLE
Lower case header files

### ISSUE THREAD

**Issue by chrisfuel** [OpenWaterAnalytics/epanet-rtx#7]
There is one issue in Linux where when you compile the epanet-rtx the code is looking for "junction.h", but the file is actually "Junction.h", and the compiler throws multiple errors because Linux is case sensitive.  A simple fix, but one I thought you might want to know about.  This happens on multiple files.  

Chris

**Comment by samhatchett** [comment]
Thanks for the extra set of eyes! I'll check it out.

**Comment by samhatchett** [comment]
@chrisfuel -- obviously you've been poking around in the code with Linux - have you generated a Makefile as part of your explorations?

**Comment by chrisfuel** [comment]
Yes, I have, once I get it to compile correctly (!), I should be able to share!  The issue is with the boost library readFile(_configFile.c_str()); and some other changes I am making.

**Comment by samhatchett** [comment]
I'll be very interested to see your changes. Incidentally, the readFile call is from libconfig -> http://freecode.com/projects/libconfigduo

Good luck, and let me know if I can be of any help.

**Comment by chrisfuel** [comment]
Old version of boost:filesystem, had to change to readFile(_configFile.string().c_str()); Just fyi.
