### ISSUE TITLE
prefetch db

### ISSUE THREAD

**Issue by jamesuber** [OpenWaterAnalytics/epanet-rtx#70]
can we review to see that the prefetch table is being truncated before the simulation, when simulations are repeated one after the other (with some changes to the ts processing in between)?

I believe I have had cases where, after a simulation, I've went and looked at a ts that I had just changed before the simulation, but the ts had lost the effects of the change. When I changed the record to none, then the effect of the change were apparent. 

This is sketchy enough that if there's likely no way this is happening, then I'll do some more specific testing. so this is really just to make sure I record the idea, at the present.

**Comment by samhatchett** [comment]
not an RTX issue
