### ISSUE TITLE
sequential calls to sqlite pr can return different results

### ISSUE THREAD

**Issue by jamesuber** [OpenWaterAnalytics/epanet-rtx#72]
This was the issue that showed up for gcww where valve setting 498684V returned an invalid point. tracking this down, it was noticed that TimeSeriesFilterSinglePoint::filterPointsInRange() had two successive calls to pointCollection() with the same range, and so should result in identical queries. The first query succeeds but the second returns a different result, ultimately causing the original request for a point to fail. 

Removing one of the above pointCollection() references solves the problem. It shouldn't be there but the question is why this occurs. Should develop a simple code that puts a couple of points into an sqlite pr and tries to retrieve them repeatedly, trying to replicate the basic problem.

**Comment by samhatchett** [comment]
this issue is a bit stale - have we seen this resurface, or do we think it got fixed in the interim?

**Comment by jamesuber** [comment]
Can't say we've investigated it, but I'm happy to close it as it hasn't been an issue.
