### ISSUE TITLE
modulartimeseries macro processor

### ISSUE THREAD

**Issue by jamesuber** [OpenWaterAnalytics/epanet-rtx#76]
"macro processor" is probably not the correct generalization.

But it occurred to me that in (possibly) developing the capability to embed TS processing chains within canvas elements, that RTX could support that with a new modulartimeseries class that would represent the timeseries processing to be done. 

This would probably be a one-to-one mapping. Some sort of graph description of the ts processing would be required, or perhaps the existing XF transformation representation is exactly what's needed.

Beyond that, I'm guessing it would hold as internal data the objects that actually perform the transformations, and would allow getting pointers to the beginning and end of the ts processing chain. Perhaps a copy constructor would be a useful device for creating an identical transformation object, given one existing.

But, this is getting well beyond my pay grade. It's just a thought.

**Comment by samhatchett** [comment]
out of scope of current RTX project. perhaps client implementations may support this higher-level feature.
