### ISSUE TITLE
Expected behavior when multiplying two streams and one stream does not have any points

### ISSUE THREAD

**Issue by jamesuber** [OpenWaterAnalytics/epanet-rtx#77]
Even if both streams do not have a clock, right now the multiplier seems to create points even in the gap. Looks like it returns the points of the one stream.

Probably expected behavior would be to not return any points in the gap.

**Comment by samhatchett** [comment]
looks like current behavior is to sample the secondary source on the basis of the time values of the primary source, and then do the multiplication. if the multiplier filter has a clock, then the result is sampled on that clock, which would interpolate across gaps. are you seeing something different?

**Comment by jamesuber** [comment]
Nope that is great. I forget about the primary/secondary distinction here, and I had the stream without the gap as primary. This current behavior actually preserves two very different behaviors, obtained by switching the sources.
