### ISSUE TITLE
moving average is broken when its source does not have a clock

### ISSUE THREAD

**Issue by jamesuber** [OpenWaterAnalytics/epanet-rtx#78]
You get jumps that appear on day boundaries. This does not depend on whether the MA itself has a clock, or not.

**Comment by samhatchett** [comment]
can you provide steps to reproduce? i'm not seeing this.

**Comment by jamesuber** [comment]
Take a source record, then resample (with 900s clock), valid range (with no clock), and moving average with 96 points (one day). Try assigning the same 900s clock to the vr and you'll notice the difference, but there should really be no difference at all cause we're just resampling the upstream resampler on the same clock.

**Comment by samhatchett** [comment]
CONFIRMED
