### ISSUE TITLE
Linux build files

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/epanet-rtx#8]
Need Linux makefile or CMake file.

**Comment by sdteffen** [comment]
There's build/linux/Makefile. Could this issue be closed?
It would be great to have the necessary autotools things in place to check for required libraries/compilers.

**Comment by sdteffen** [comment]
Noticed one more thing: There's no "make install", but e.g. the libepanetrtx.so file needs to be "installed" in order for the binaries to work.
