### ISSUE TITLE
Problems compiling

### ISSUE THREAD

**Issue by chrisfuel** [OpenWaterAnalytics/epanet-rtx#9]
Under gcc the following typical lines of code will fail:

friend std::ostream& operator << (std::ostream & out, TimeSeries &ts);

This is because gcc (2010) will not allow you to forward declare across namespace boundaries.

Also, if your inp file has no reservoirs,an "abort" will be raised in setSimulationParameters. An easy fix is to add a single reservoir to your .inp file.

**Comment by samhatchett** [comment]
Thanks for raising this issue. Does it look like moving the `operator<<` overload outside the class declaration (but inside the namespace) would work? Also, what version of GCC are you using? My GCC4.2 handles this just fine.

As for the second issue you raise, I'd suggest that it be moved into its own Issue so it can be tracked better. However, a reservoir-less network works for me. Maybe you can open a new Issue and list the steps required to reproduce the bug.

Thanks again -- and also, who are you? This is kind of a niche of a niche project, so I admit i'm curious about your identity and background.

s

**Comment by chrisfuel** [comment]
Here's the error.  I believe we are running gcc 4.4.6

std::ostream& RTX::operator<<(std::ostream&, RTX::Clock&)' should have been declared inside 'RTX'

I "fixed" it by rewriting  clock as follows:

namespace RTX {
std::ostream& operator<< (std:;ostream &out, Clock &clock);
}

class Clock {
public:  
  RTX_SHARED_POINTER(Clock);
  friend std::ostream& RTX::operator<< (std::ostream &out, Clock & clock):

It may have not been the best fix, but it worked.  :-)

Send me an email, I will let you know about what I am doing & where I am at.  

cjs

**Comment by samhatchett** [comment]
commit d68e0e9 should fix this issue, but i'll leave it open until I hear back. And I don't have your email address - it's not published on your profile page. feel free to send me your addy.

**Comment by sdteffen** [comment]
Using gcc 4.8.1 and an updated Makefile ( pull request 35 ), I was able to compile and run the demo. I think this issue can be closed.
