### ISSUE TITLE
Units of a gain time series with no_units units of the gain factor

### ISSUE THREAD

**Issue by jamesuber** [OpenWaterAnalytics/epanet-rtx#91]
If you pass a constant time series with units into a gain with no_units gain factor, the result has no_units. Similarly, if you pass a constant time series with no_units into a gain with any units for the gain factor, the result has no_units. This makes sense.

A multiplier with units passed into a gain with no_units as the gain factor does not yield no_units -- the units remain the same as that of the multiplier. This seems not to be right.

**Comment by samhatchett** [comment]
this is more of an applications issue. use `RTX::Units::unitOfType()` to specify arbitrary units. this works as long as the string is valid.
