### ISSUE TITLE
pointAtOrBefore() problem associated with multiplier receiving constant with no clock

### ISSUE THREAD

**Issue by jamesuber** [OpenWaterAnalytics/epanet-rtx#92]
Have a repeatable case (HCWD) where simulation is affected by whether a pump setting is assigned by a time series, or by that same series after being multiplied by a constant 1.0 series, when the 1.0 constant series has no clock. Visually these two series are identical when using the points() method. However the simulation is affected, which uses pointAtOrBefore(). This problem disappears when the constant is given a clock.

**Comment by samhatchett** [comment]
i don't think a Constant makes sense without a clock. Something needs to set the time indexes at which points are available.

**Comment by jamesuber** [comment]
That's good.
