### ISSUE TITLE
statistical descriptions over ensembles of elements

### ISSUE THREAD

**Issue by jamesuber** [OpenWaterAnalytics/epanet-rtx#94]
RTX is currently weak in this area; should think about some use cases and strategies. E.g.,
- computing percentiles of errors over different sets of data streams: tanks, all nodes, all DMA nodes, all flow/boundary flow/pressure/level measurements or those within a DMA or on the boundary of a DMA.

Not sure if this "breaks the paradigm" -- It doesn't _have_ to since these are all standard statistical operations that use and produce time series, but are defined over an ensemble of series as opposed to a time window.

But I'll admit that this sounds pretty frightening, so maybe all of these sorts of things do need to be done eventually in something like influxdb.

**Comment by samhatchett** [comment]
I could argue that this is a downstream "analytics application" that would do better in a more expressive environment (like with influx aggregate queries). However, I could also see this functionality being wrapped by RTX somehow. Good thoughts.
