### ISSUE TITLE
Model element statuses can be overridden by Epanet if specified in a control, even if control is disabled

### ISSUE THREAD

**Issue by jamesuber** [OpenWaterAnalytics/epanet-rtx#96]
Found this out by noticing that a pump that had a status boundary = 0 could be turned on by Epanet, e.g. 

```
        Pump TR_PUMP_1 switched from closed to open
```

apparently because the element appears in a disabled control rule. If the control is completely eliminated then Epanet leaves it alone, as expected.

Bottom line is that disabling control rules is  not completely "disabling" them, as currently implemented. Not sure if this is really an RTX issue or better in Epanet, but it's here since RTX is the thing that cares.

**Comment by jamesuber** [comment]
Case where this happens is flint-4.inp with controls uncommented, simulation from 3/10/2016 18:00 through 3/13/2016 6:00

**Comment by samhatchett** [comment]
fixed in https://github.com/samhatchett/EPANET/commit/ce7d3f895800355afb9812bb0ceb78ed6fd8cb96
