### ISSUE TITLE
resampling error

### ISSUE THREAD

**Issue by jamesuber** [OpenWaterAnalytics/epanet-rtx#99]
gaps in a curve that is resampling - this is valve V114 in Flint.
![screen shot 2016-06-23 at 8 45 05 am](https://cloud.githubusercontent.com/assets/2408457/16303503/ee8c2aca-391e-11e6-890e-641e2e92a237.png)

**Comment by samhatchett** [comment]
Are all the input values within the proper range of the curve?

**Comment by jamesuber** [comment]
Yeah the curve goes from 0-100 and if I insert a valid range between the data source and the curve, I get the same thing.

**Comment by samhatchett** [comment]
thanks, this looks like a familiar day-boundary problem with upstream range-expansion. I'm on it!

**Comment by samhatchett** [comment]
this was due to the gap sizes being larger than expected. defaults have been adjusted.
